# Required minimum perl version
requires 'perl' => '5.020';

# Game Engine GUI & Core Loop Dependencies
requires 'Gtk3'           => '0.01';
requires 'Glib'           => '1.320';
requires 'Time::HiRes'    => '0';

# Asset Management & Sound Playback Dependencies
requires 'File::ShareDir' => '1.118';

# Development and Testing Environments
on 'test' => sub {
    requires 'Test::More' => '0.98';
};
